server:
  port: 8081

upload:
  path: uploads/

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  application:
    name: Studentservices

  datasource:
    url: jdbc:mysql://localhost:3308/student_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: 84.46.241.34
    port: 5672
    username: admin
    password: cambia_esta_password

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: bab84ba3d66ad5
    password: 12aa6c462a66b2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

learning-engine:
  url: https://lexicological-semestrial-johnathan.ngrok-free.dev

espocrm:
  url: http://localhost:8082
  api-key: 1bd355c4ec1cf60dd20374d9b5a53bc2